#!/usr/bin/env bash

set -exuo pipefail

image="ghcr.io/ublue-os/${1}"
unit="${2}"

function send-notification {
    for user in $(w --no-header -u | awk '{print $1}' | grep -v root | sort | uniq); do
        systemd-run --machine="${user}"@.host --user notify-send "$1" "$2"
    done
}

send-notification "System Rebase" "Starting rebase to $1"

# Writing directly to /run/ublue-rebase causes weird non-atomic behavior when reading the file back with Qt
echo "$1 $unit" > /run/ublue-rebase.lock
mv /run/ublue-rebase.lock /run/ublue-rebase

sleep 30

#send-notification "System Rebase" "Rebase failed. Check logs for more details. TODO: put path here"
#exit 1

send-notification "System Rebase" "Rebase completed. Please reboot to use the new image."


#echo bootc switch --enforce-container-sigpolicy "${image}"

#if /usr/bin/grep "^LockLayering=true" /etc/rpm-ostreed.conf &> /dev/null; then
#    bootc switch --enforce-container-sigpolicy "${image}"
#else
#    rpm-ostree rebase ostree-image-signed:docker://"${image}"
#fi
